language: go

go:
  - release
  - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover

script:
    - $HOME/gopath/bin/goveralls -repotoken MSToT9De9SIxTAH8BD3JsN68xfWAPEqDP

notifications:
  email:
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always