language: go

sudo: false

go:
  - release
  - tip

before_install:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - go get -t simonwaldherr.de/go/GolangSortingVisualization

install:
    - go get -t simonwaldherr.de/go/GolangSortingVisualization
    - go get github.com/modocache/gover

script:
    - go test -v
    - $HOME/gopath/bin/gover
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci

notifications:
  email:
    recipients:
      - travis@simon.waldherr.eu
    on_success: always
    on_failure: always